import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Fustat, Geist, Onest } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const fustat = Fustat({
  variable: "--font-fustat",
  subsets: ["latin"],
});

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "La Revuelta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <link rel="icon" href="/favicon/favicon.ico" />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link rel="apple-touch-icon" href="/favicon/apple-touch-icon.png" />

        <link rel="manifest" href="/favicon/site.webmanifest" />
        {/* <link
          rel="preload"
          as="image"
          href="/fotos/session.webp"
          type="image/webp"
        /> */}
      </head>
      <body
        className={`${geistSans.variable} ${fustat.variable} ${onest.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
